export const FETCHING_ALL_HEROS_REQUEST = 'FETCHING_ALL_HEROS_REQUEST';
export const FETCHING_ALL_HEROS_SUCCESS = 'FETCHING_ALL_HEROS_SUCCESS';
export const FETCHING_ALL_HEROS_FAILURE = 'FETCHING_ALL_HEROS_FAILURE';

export const FETCHING_HERO_PROFILE_REQUEST = 'FETCHING_HERO_PROFILE_REQUEST';
export const FETCHING_HERO_PROFILE_SUCCESS = 'FETCHING_HERO_PROFILE_SUCCESS';
export const FETCHING_HERO_PROFILE_FAILURE = 'FETCHING_HERO_PROFILE_FAILURE';

export const UPDATE_HERO_PROFILE_REQUEST = 'UPDATE_HERO_PROFILE_REQUEST';
export const UPDATE_HERO_PROFILE_SUCCESS = 'UPDATE_HERO_PROFILE_SUCCESS';
export const UPDATE_HERO_PROFILE_FAILURE = 'UPDATE_HERO_PROFILE_FAILURE';

export const PLUS_ABILITY_STATUS = 'PLUS_ABILITY_STATUS';
export const MINUS_ABILITY_STATUS = 'MINUS_ABILITY_STATUS';
